import { CommonModule } from "@angular/common";
import { HttpClient } from '@angular/common/http';
import { AfterViewInit, Component, ElementRef, ViewChild } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { FeatureCollection, GeoJsonProperties, Point } from 'geojson';
import mapboxgl from "mapbox-gl";
import { MapCleanupService } from '../../core/map-cleanup.service';
import { TimelapseService } from '../../core/timelapse.service';
import { BloomingHotspot } from "../bloomingHotspot.model";
import { HotspotService } from '../hotspot-service';
import { PollinatorRoute } from "../pollinatorRoute.model";

 

@Component({
  selector: 'app-mapa-component',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './mapa.html',
  styleUrls: ['./mapa.scss']
})
export class Mapa implements AfterViewInit {
  cityQuery: string = '';
  private readonly cityCoords: { [key: string]: [number, number] } = {
    'madrid': [-3.7038, 40.4168],
    'bilbao': [-2.935, 43.263],
    'sevilla': [-5.9845, 37.3891],
    'zaragoza': [-0.8773, 41.6561],
    'malaga': [-4.4214, 36.7213],
    'jaen': [-3.5985, 37.1773],
    'asturias': [-5.8593, 43.3614],
    'galicia': [-7.5593, 42.3601],
    'gran canaria': [-15.43, 28.1248],
    'la palma': [-17.9077, 27.7648]
  };

  constructor(
    private readonly hotspotService: HotspotService,
    private readonly mapCleanup: MapCleanupService,
    private readonly timelapseService: TimelapseService,
    private http: HttpClient
  ) {
    this.mapCleanup.clear$.subscribe(() => this.clearHotspots());
  }

  goToCity(): void {
    if (!this.cityQuery) return;
    const city = this.cityQuery.trim().toLowerCase();
    if (this.cityCoords[city]) {
      this.map.flyTo({ center: this.cityCoords[city], zoom: 11, speed: 1.2 });
    }
    this.cityQuery = '';
  }
  @ViewChild('mapContainer', { static: false }) mapContainer!: ElementRef<HTMLDivElement>;

  map!: mapboxgl.Map;
  // If configured, the remote URL will be used to load real hotspots
  // By default, we point to GLOBE (geojson) for auto-loading in demos/dev
  remoteHotspotUrl: string | null = 'https://api.globe.gov/search/v1/samples?geojson=TRUE'; // example: 'https://api.example.com/hotspots'
  // Last GeoJSON generated by remote load (useful for download)
  lastRemoteGeojson?: FeatureCollection<Point, GeoJsonProperties> = undefined;
  // Temporary fields to create local hotspots in demo
  newHotspotLat: number | null = null;
  newHotspotLon: number | null = null;
  newHotspotName: string = '';
  newHotspotIntensity: number = 0.5;
  currentMonth: number = 5; // May by default
  timelapseRunning: boolean = false;
  timelapseIntervalId: number | null = null;
  isAnimating: boolean = false;
  bloomingData: BloomingHotspot[] = [];
  pollinatorRoutes: PollinatorRoute[] = [];
  panelCollapsed: boolean = false;
  isLoading: boolean = true;
  loadingProgress: number = 0;

  // Simulated blooming data for Spain
  private readonly bloomingHotspots: BloomingHotspot[] = [
    // Spring (April-June)
    { lat: 37.1773, lon: -3.5985, intensity: 0.9, name: "Jaen Fields", bloomPeriod: "April-May", species: ["Olive Tree", "Rosemary", "Thyme"], pollinatorCount: 15000 },
    { lat: 41.6561, lon: -0.8773, intensity: 0.8, name: "Ebro Valley", bloomPeriod: "May-June", species: ["Almond Tree", "Lavender"], pollinatorCount: 12000 },
    { lat: 40.4637, lon: -3.7492, intensity: 0.7, name: "Madrid Mountains", bloomPeriod: "April-June", species: ["Rockrose", "Broom"], pollinatorCount: 8000 },

    // Summer (July-August)
    { lat: 43.3614, lon: -5.8593, intensity: 0.6, name: "Asturias", bloomPeriod: "July-August", species: ["Heather", "Chestnut tree"], pollinatorCount: 10000 },
    { lat: 42.3601, lon: -7.5593, intensity: 0.8, name: "Galicia", bloomPeriod: "July-September", species: ["Eucalyptus", "Mimosa"], pollinatorCount: 14000 },

    // Autumn (September-October)
    { lat: 36.7213, lon: -4.4214, intensity: 0.7, name: "Malaga", bloomPeriod: "September-October", species: ["Orange blossom", "Strawberry tree"], pollinatorCount: 9000 },

    // Winter (December-February)
    { lat: 28.1248, lon: -15.4300, intensity: 0.5, name: "Gran Canaria", bloomPeriod: "December-February", species: ["Bougainvillea", "Tajinaste"], pollinatorCount: 6000 },
    { lat: 27.7648, lon: -17.9077, intensity: 0.6, name: "La Palma", bloomPeriod: "January-March", species: ["Almond blossom"], pollinatorCount: 7000 },
    // Example moderate hotspot (should appear orange)
    { lat: 40.4168, lon: -3.7038, intensity: 0.45, name: "Madrid - Moderate", bloomPeriod: "April-June", species: ["Urban Park"], pollinatorCount: 4000, status: 'moderate' },
    // Example critical hotspot (should appear red)
    { lat: 37.3875, lon: -5.9962, intensity: 0.15, name: "Critical Example Zone", bloomPeriod: "January-December", species: ["None"], pollinatorCount: 200, status: 'critical' }
  ];

  ngAfterViewInit(): void {
    // Start loading simulation
    this.simulateLoading();

    // Continue with map initialization after loading
    setTimeout(() => {
      this.initializeMap();
    }, 5500); // Wait for the loading animation to finish
  }

  private initializeMap(): void {
    (mapboxgl as any).accessToken = 'pk.eyJ1Ijoic2FoaXZhIiwiYSI6ImNtZzl3cXFwaDBpOG8ybHNneGFwZ3ZqOTUifQ.UrldzEHRjHkw2CiMeAyR-Q';

    // Space entry effect: starts very far and with rotation
    this.map = new mapboxgl.Map({
      container: this.mapContainer.nativeElement,
      style: 'mapbox://styles/mapbox/satellite-streets-v12',
      center: [0, 30], // Global view
      zoom: 1.5,
      pitch: 75,
      bearing: 120,
      antialias: true
    });

    this.map.on('style.load', () => {
      // Add atmospheric fog for dramatic effect
      this.map.setFog({
        'range': [0.8, 8],
        'color': '#f8f0e3',
        'horizon-blend': 0.5
      });

      // Animate to Spain view with zoom and rotation
      setTimeout(() => {
        this.map.flyTo({
          center: [-3.7038, 40.4168],
          zoom: 6,
          pitch: 45,
          bearing: 0,
          speed: 0.7,
          curve: 1.8,
          essential: true
        });
      }, 1200);

      this.initializeBeeziDemo();
    });
  }

  /** Clears layers, sources, popups, and animations related to hotspots */
    clearHotspots(): void {
      try {
        this.isAnimating = false;
        if ((this as any).animationFrameId) {
          cancelAnimationFrame((this as any).animationFrameId);
          (this as any).animationFrameId = undefined;
        }

        if (this.map) {
          const removeIfExists = (id: string) => {
            try { if (this.map.getLayer(id)) this.map.removeLayer(id); } catch (err) { console.debug('removeLayer ignored', err); }
            try { if (this.map.getSource(id)) this.map.removeSource(id); } catch (err) { console.debug('removeSource ignored', err); }
          };
          ['blooming-circles', 'blooming-heatmap', 'blooming-hotspots', 'hotspots', 'routes-lines', 'routes'].forEach(removeIfExists);
        }

        try {
          const popups = document.querySelectorAll('.mapboxgl-popup');
          popups.forEach(p => p.remove());
        } catch (e) { console.debug('closing popups ignored', e); }
  // Ensure that the timelapse also stops
        if (this.timelapseIntervalId) {
          clearInterval(this.timelapseIntervalId as any);
          this.timelapseIntervalId = null;
          this.timelapseRunning = false;
        }
      } catch (e) {
        console.debug('clearHotspots error', e);
      }
    }

  initializeBeeziDemo(): void {
    // Load current blooming data
    // If a remote URL is configured, try to load remote data, otherwise use simulated data
    if (this.remoteHotspotUrl) {
      this.loadRemoteHotspots(this.remoteHotspotUrl);
    } else {
      this.updateBloomingData();
    }
    
    // Crear rutas de polinizadores
    this.createPollinatorRoutes();
    
    // Añadir capas de visualización
    this.addBloomingLayer();
    this.addPollinatorLayer();
    this.addHeatmapLayer();
    
    // Iniciar animación del "pulso de vida"
    this.startBloomPulseAnimation();
    
    // Añadir controles interactivos
    this.addCustomControls();
  }

  // Constructor fusionado arriba con ngx-translate y servicios

  public loadRemoteHotspots(apiUrl: string): void {
    if (!this.hotspotService) {
      // Servicio no inyectado; usar datos simulados
      this.updateBloomingData();
      return;
    }

    const isGlobe = /globe\.gov/i.test(apiUrl);
    const obs = isGlobe ? this.hotspotService.getHotspotsFromGlobeApi(apiUrl) : this.hotspotService.getHotspotsFromApi(apiUrl);

    obs.subscribe({
      next: (remoteHotspots) => {
        if (remoteHotspots && remoteHotspots.length > 0) {
          this.bloomingData = remoteHotspots;
        } else {
          this.updateBloomingData();
        }

        // Actualizar la fuente si ya existe
        const geojson: FeatureCollection<Point, GeoJsonProperties> = {
          type: "FeatureCollection",
          features: this.bloomingData.map(hotspot => ({
            type: "Feature",
            geometry: { type: "Point", coordinates: [hotspot.lon, hotspot.lat] },
            properties: { name: hotspot.name, intensity: hotspot.intensity, status: (hotspot as any).status, species: hotspot.species.join(', '), pollinatorCount: hotspot.pollinatorCount, bloomPeriod: hotspot.bloomPeriod }
          }))
        };

        try {
          (this.map.getSource('blooming-hotspots') as mapboxgl.GeoJSONSource)?.setData(geojson);
        } catch (e) {
          // Si la fuente no existe aún, la creación posterior la usará
          console.warn('No se pudo actualizar la fuente blooming-hotspots:', e);
        }
          // Guardar geojson para descarga
            this.lastRemoteGeojson = geojson;
            // mostrar/activar botón de descarga
            const dlBtn = document.getElementById('download-geojson-btn') as HTMLButtonElement | null;
            if (dlBtn) dlBtn.style.display = this.bloomingData.length > 0 ? 'inline-block' : 'none';
          console.log('Primer hotspot mapeado:', this.bloomingData[0]);
    // Actualizar UI de estado y conteo
    const countEl = document.getElementById('remote-count');
    const statusEl = document.getElementById('remote-load-status');
    if (countEl) countEl.textContent = String(this.bloomingData.length);
    if (statusEl) statusEl.textContent = `Estado: cargados ${this.bloomingData.length} hotspots`;
      },
      error: (err) => {
        console.error('Error cargando hotspots remotos:', err);
        this.updateBloomingData();
        const statusEl = document.getElementById('remote-load-status');
        if (statusEl) statusEl.textContent = 'Estado: error cargando datos (ver consola)';
      }
    });
  }

  /** Añadir un hotspot local a bloomingData y actualizar la fuente/descarga */
  addLocalHotspot(): void {
    if (this.newHotspotLat === null || this.newHotspotLon === null) {
      alert('Please enter valid coordinates. Use the map center if needed.');
      return;
    }

    const h: BloomingHotspot = {
      lat: Number(this.newHotspotLat),
      lon: Number(this.newHotspotLon),
      intensity: Math.max(0, Math.min(1, Number(this.newHotspotIntensity) || 0.5)),
      name: this.newHotspotName || 'Hotspot local',
      bloomPeriod: '',
      species: [],
      pollinatorCount: 0,
      status: undefined
    } as BloomingHotspot;

    // Añadir al arreglo y actualizar fuente si existe
    this.bloomingData = [...this.bloomingData, h];
    const geojson: FeatureCollection<Point, GeoJsonProperties> = {
      type: 'FeatureCollection',
      features: this.bloomingData.map(hotspot => ({ type: 'Feature', geometry: { type: 'Point', coordinates: [hotspot.lon, hotspot.lat] }, properties: { name: hotspot.name, intensity: hotspot.intensity, status: (hotspot as any).status, species: hotspot.species.join(', '), pollinatorCount: hotspot.pollinatorCount, bloomPeriod: hotspot.bloomPeriod } }))
    };

    try {
      (this.map.getSource('blooming-hotspots') as mapboxgl.GeoJSONSource)?.setData(geojson);
    } catch (e) {
      console.warn('No se pudo actualizar la fuente blooming-hotspots al añadir local:', e);
    }

    // Guardar y habilitar descarga
    this.lastRemoteGeojson = geojson;
    const dlBtn = document.getElementById('download-geojson-btn') as HTMLButtonElement | null;
    if (dlBtn) dlBtn.style.display = 'inline-block';

    // Limpiar formulario
    this.newHotspotLat = null;
    this.newHotspotLon = null;
    this.newHotspotName = '';
    this.newHotspotIntensity = 0.5;
  }

  /** Toma el centro de la vista actual del mapa y lo prepara como nuevo hotspot */
  setNewHotspotFromCenter(): void {
    if (!this.map) return;
    const center = this.map.getCenter();
    this.newHotspotLat = Number(center.lat.toFixed(6));
    this.newHotspotLon = Number(center.lng.toFixed(6));
  }

  /** Descargar el último GeoJSON mapeado (si existe) */
  downloadLastGeojson(): void {
    if (!this.lastRemoteGeojson) {
  alert('No GeoJSON available for download.');
      return;
    }
    const dataStr = JSON.stringify(this.lastRemoteGeojson, null, 2);
    const blob = new Blob([dataStr], { type: 'application/geo+json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'blooming-hotspots.geojson';
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  updateBloomingData(): void {
    // Filtrar datos según el mes actual
    this.bloomingData = this.bloomingHotspots.filter(hotspot => {
      const bloomMonths = this.getBloomMonths(hotspot.bloomPeriod);
      return bloomMonths.includes(this.currentMonth);
    });
  }

  getBloomMonths(period: string): number[] {
    const monthMap: {[key: string]: number} = {
      'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6,
      'July': 7, 'August': 8, 'September': 9, 'October': 10, 'November': 11, 'December': 12
    };
    
    const months: number[] = [];
    const parts = period.split('-');
    if (parts.length === 2) {
      const start = monthMap[parts[0]];
      const end = monthMap[parts[1]];
      
      for (let i = start; i <= end; i++) {
        months.push(i);
      }
    }
    return months;
  }

  createPollinatorRoutes(): void {
    this.pollinatorRoutes = [
      {
        type: "Feature",
        geometry: {
          type: "LineString",
          coordinates: [
            [-3.7038, 40.4168], // Madrid
            [-2.9350, 43.2630], // Bilbao
            [-5.8593, 43.3614], // Asturias
            [-7.5593, 42.3601]  // Galicia
          ]
        },
        properties: { name: "Ruta Norte", species: "Apis mellifera", active: true }
      },
      {
        type: "Feature", 
        geometry: {
          type: "LineString",
          coordinates: [
            [-3.5985, 37.1773], // Jaén
            [-4.4214, 36.7213], // Málaga
            [-5.9845, 37.3891], // Sevilla
            [-0.8773, 41.6561]  // Zaragoza
          ]
        },
        properties: { name: "Ruta Sur", species: "Apis mellifera", active: true }
      }
    ];
  }

  addBloomingLayer(): void {
    const geojson: FeatureCollection<Point, GeoJsonProperties> = {
      type: "FeatureCollection",
      features: this.bloomingData.map(hotspot => ({
        type: "Feature",
        geometry: { 
          type: "Point", 
          coordinates: [hotspot.lon, hotspot.lat] 
        },
        properties: { 
          name: hotspot.name,
          intensity: hotspot.intensity,
          status: hotspot.status,
          species: hotspot.species.join(', '),
          pollinatorCount: hotspot.pollinatorCount,
          bloomPeriod: hotspot.bloomPeriod
        }
      }))
    };

    this.map.addSource('blooming-hotspots', { 
      type: 'geojson', 
      data: geojson 
    });

    // Capa principal de hotspots con efecto pulsante
    this.map.addLayer({
      id: 'blooming-circles',
      type: 'circle',
      source: 'blooming-hotspots',
      paint: {
        'circle-radius': [
          'interpolate',
          ['linear'],
          ['get', 'intensity'],
          0, 10,
          1, 40
        ],
        // Priorizar color por 'status' si existe: critico -> rojo, moderado -> naranja, bajo -> amarillo.
        // Si no hay 'status', se usa la interpolación por 'intensity' existente.
        'circle-color': [
          'case',
          ['==', ['get', 'status'], 'critico'], '#FF1744',
          ['==', ['get', 'status'], 'moderado'], '#FF6B35',
          ['==', ['get', 'status'], 'bajo'], '#FFE135',
          /* fallback por intensidad */
          ['interpolate', ['linear'], ['get', 'intensity'], 0, '#FFE135', 0.5, '#FF6B35', 1, '#FF1744']
        ],
        'circle-opacity': 0.7,
        'circle-stroke-width': 2,
        'circle-stroke-color': '#FFFFFF',
        'circle-stroke-opacity': 0.8
      }
    });

    // Añadir popups informativos
    this.map.on('click', 'blooming-circles', (e) => {
      const properties = e.features![0].properties!;
      const coordinates = (e.features![0].geometry as any).coordinates.slice();

      new mapboxgl.Popup()
        .setLngLat(coordinates)
        .setHTML(`
          <div style="padding: 10px; max-width: 250px;">
            <h3 style="margin: 0 0 10px 0; color: #2E7D32;">🌺 ${properties['name']}</h3>
            <p><strong>Blooming period:</strong> ${properties['bloomPeriod']}</p>
            <p><strong>Species:</strong> ${properties['species']}</p>
            <p><strong>Pollinators:</strong> ${properties['pollinatorCount'].toLocaleString()}</p>
            <p><strong>Intensity:</strong> ${(properties['intensity'] * 100).toFixed(0)}%</p>
          </div>
        `)
        .addTo(this.map);
    });
  }

  addPollinatorLayer(): void {
    this.pollinatorRoutes.forEach((route, index) => {
      this.map.addSource(`pollinator-route-${index}`, {
        type: 'geojson',
        data: route
      });

      this.map.addLayer({
        id: `pollinator-path-${index}`,
        type: 'line',
        source: `pollinator-route-${index}`,
        layout: {
          'line-join': 'round',
          'line-cap': 'round'
        },
        paint: {
          'line-color': '#4CAF50',
          'line-width': 4,
          'line-opacity': 0.8,
          'line-dasharray': [2, 2] // Línea discontinua para simular movimiento
        }
      });

      // Añadir puntos animados que se mueven por las rutas
      this.animatePollinatorMovement(route, index);
    });
  }

  addHeatmapLayer(): void {
    // Crear mapa de calor para mostrar concentración de actividad
    this.map.addLayer({
      id: 'blooming-heatmap',
      type: 'heatmap',
      source: 'blooming-hotspots',
      maxzoom: 9,
      paint: {
        'heatmap-weight': [
          'interpolate',
          ['linear'],
          ['get', 'intensity'],
          0, 0,
          1, 1
        ],
        'heatmap-intensity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0, 1,
          9, 3
        ],
        'heatmap-color': [
          'interpolate',
          ['linear'],
          ['heatmap-density'],
          0, 'rgba(255, 225, 53, 0)',
          0.2, 'rgba(255, 225, 53, 0.2)',
          0.4, 'rgba(255, 107, 53, 0.4)',
          0.6, 'rgba(255, 23, 68, 0.6)',
          0.8, 'rgba(183, 28, 28, 0.8)'
        ],
        'heatmap-radius': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0, 2,
          9, 20
        ],
        'heatmap-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          7, 1,
          9, 0
        ]
      }
    }, 'blooming-circles');
  }

  startBloomPulseAnimation(): void {
    let pulseScale = 1;
    let growing = true;

    const animate = () => {
      if (growing) {
        pulseScale += 0.02;
        if (pulseScale >= 1.3) growing = false;
      } else {
        pulseScale -= 0.02;
        if (pulseScale <= 1) growing = true;
      }

      this.map.setPaintProperty('blooming-circles', 'circle-radius', [
        'interpolate',
        ['linear'],
        ['get', 'intensity'],
        0, 10 * pulseScale,
        1, 40 * pulseScale
      ]);

      if (this.isAnimating) {
        requestAnimationFrame(animate);
      }
    };

    this.isAnimating = true;
    animate();
  }

  animatePollinatorMovement(route: PollinatorRoute, routeIndex: number): void {
    const coordinates = route.geometry.coordinates;
    let currentPoint = 0;
    let progress = 0;

    const moveIcon = () => {
      if (currentPoint >= coordinates.length - 1) {
        currentPoint = 0;
        progress = 0;
      }

      const startCoord = coordinates[currentPoint];
      const endCoord = coordinates[currentPoint + 1];
      
      if (endCoord) {
        const currentCoord = [
          startCoord[0] + (endCoord[0] - startCoord[0]) * progress,
          startCoord[1] + (endCoord[1] - startCoord[1]) * progress
        ];

        // Crear o actualizar el marcador de abeja
        const beeIcon = document.createElement('div');
        beeIcon.className = 'bee-marker';
        beeIcon.innerHTML = '🐝';
        beeIcon.style.fontSize = '20px';
        beeIcon.style.textShadow = '1px 1px 2px rgba(0,0,0,0.7)';

        if (!this.map.getSource(`bee-${routeIndex}`)) {
          this.map.addSource(`bee-${routeIndex}`, {
            type: 'geojson',
            data: {
              type: 'Feature',
              geometry: {
                type: 'Point',
                coordinates: currentCoord
              },
              properties: {}
            }
          });

          new mapboxgl.Marker(beeIcon)
            .setLngLat(currentCoord as [number, number])
            .addTo(this.map);
        } else {
          (this.map.getSource(`bee-${routeIndex}`) as mapboxgl.GeoJSONSource).setData({
            type: 'Feature',
            geometry: {
              type: 'Point',
              coordinates: currentCoord
            },
            properties: {}
          });
        }

        progress += 0.01;
        if (progress >= 1) {
          currentPoint++;
          progress = 0;
        }
      }

      if (this.isAnimating) {
        setTimeout(moveIcon, 50); // Velocidad de animación
      }
    };

    moveIcon();
  }

  addCustomControls(): void {
    // Control de slider temporal
    const timeControl = document.createElement('div');
    timeControl.className = 'mapboxgl-ctrl mapboxgl-ctrl-group';
    timeControl.innerHTML = `
      <div style="padding: 10px; background: white; border-radius: 4px; min-width: 200px;">
  <h4 style="margin: 0 0 10px 0; color: #2E7D32;">🕐 Time control</h4>
   <input type="range" min="1" max="12" value="${this.currentMonth}" 
     style="width: 100%;" id="monthSlider" name="monthSlider">
        <div style="display: flex; justify-content: space-between; font-size: 12px; margin-top: 5px;">
          <span>Jan</span><span>Dec</span>
        </div>
        <div id="currentMonth" style="text-align: center; font-weight: bold; margin-top: 5px;">
          ${['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][this.currentMonth-1]}
        </div>
      </div>
    `;

    // Panel de estadísticas
    const statsPanel = document.createElement('div');
    statsPanel.className = 'mapboxgl-ctrl';
    statsPanel.innerHTML = `
      <div style="padding: 15px; background: rgba(255,255,255,0.95); border-radius: 8px; min-width: 250px; backdrop-filter: blur(10px);">
  <h3 style="margin: 0 0 15px 0; color: #2E7D32; text-align: center;">🌍 Ecosystem Dashboard</h3>
        <div id="stats-content">
          <div style="margin-bottom: 10px;">
            <strong>Active hotspots:</strong> <span id="active-hotspots">${this.bloomingData.length}</span>
          </div>
          <div style="margin-bottom: 10px;">
            <strong>Total pollinators:</strong> <span id="total-pollinators">${this.getTotalPollinators().toLocaleString()}</span>
          </div>
          <div style="margin-bottom: 10px;">
            <strong>Risk zones:</strong> <span id="risk-zones">${this.getRiskZones()}</span>
          </div>
          <div style="margin-bottom: 15px;">
            <strong>Status:</strong> <span id="general-status" style="color: #4CAF50;">Stable</span>
          </div>
          <div style="display: flex; gap: 6px; margin-bottom: 8px;">
            <input id="remoteApiUrlInput" name="remoteApiUrl" type="text" value="https://api.globe.gov/search/v1/measurement/protocol/measureddate/measurementcountry/?protocols=phenological_gardens&startdate=1995-01-01&enddate=2005-01-01&countrycode=ABW&geojson=TRUE&sample=TRUE" style="flex:1; padding:6px; font-size:12px;" />
            <button id="load-remote-hotspots-btn" title="Load remote hotspots" style="padding: 6px 8px; background: #1976D2; color: white; border: none; border-radius: 4px; cursor: pointer;">Load remote hotspots</button>
          </div>
          <div style="font-size:12px; margin-bottom:8px;">
            <span id="remote-load-status" style="color:#333;">Inactive</span>
            <span style="float:right;">Results: <span id="remote-count">0</span></span>
          </div>
          <div style="display:flex; gap:8px; margin-bottom:8px;">
            <button id="download-geojson-btn" style="display:none; padding:6px 8px; background:#4CAF50; color:white; border:none; border-radius:4px; cursor:pointer;">Download .geojson</button>
            <button id="copy-console-btn" style="padding:6px 8px; background:#9C27B0; color:white; border:none; border-radius:4px; cursor:pointer;">Copy to console</button>
          </div>
          <button id="emergency-btn" style="width: 100%; padding: 8px; background: #FF5722; color: white; border: none; border-radius: 4px; cursor: pointer;">
            🚨 Emergency
          </button>
        </div>
      </div>
    `;

    this.map.addControl({
      onAdd: () => timeControl,
      onRemove: () => {}
    } as any, 'top-left');

    this.map.addControl({
      onAdd: () => statsPanel,
      onRemove: () => {}
    } as any, 'top-right');

    // Event listeners
    setTimeout(() => {
      const slider = document.getElementById('monthSlider') as HTMLInputElement;
      const monthDisplay = document.getElementById('currentMonth')!;
      const emergencyBtn = document.getElementById('emergency-btn')!;

      slider?.addEventListener('input', (e) => {
        const target = e.target as HTMLInputElement;
        this.currentMonth = parseInt(target.value);
        monthDisplay.textContent = this.getMonthName(this.currentMonth);
        this.updateVisualization();
      });

      emergencyBtn?.addEventListener('click', () => {
        this.triggerEmergencyProtocol();
      });

      const loadBtn = document.getElementById('load-remote-hotspots-btn') as HTMLButtonElement | null;
      const urlInput = document.getElementById('remoteApiUrlInput') as HTMLInputElement | null;
      loadBtn?.addEventListener('click', () => {
        let url = urlInput?.value?.trim();
        if (!url) {
  alert('Please enter a valid API URL.');
          return;
        }

        // Si el usuario puso una URL absoluta que apunta a localhost (o 127.0.0.1), convertirla a ruta relativa
        if (/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?/i.test(url)) {
          // Reemplazar el origen por vacío para usar la ruta relativa y aprovechar el proxy dev
          url = url.replace(/^https?:\/\/[^/]+/i, '');
        }

        // Guardar y cargar
        this.remoteHotspotUrl = url;
        // Actualizar UI: estado
        const statusEl = document.getElementById('remote-load-status');
        if (statusEl) statusEl.textContent = 'Estado: cargando...';
        this.loadRemoteHotspots(url);
      });
      const dlBtn = document.getElementById('download-geojson-btn') as HTMLButtonElement | null;
      dlBtn?.addEventListener('click', () => {
        if (!this.lastRemoteGeojson) {
          alert('No GeoJSON could be loaded.');
          return;
        }
        const dataStr = JSON.stringify(this.lastRemoteGeojson, null, 2);
        const blob = new Blob([dataStr], { type: 'application/geo+json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'hotspots_remote.geojson';
        a.click();
        URL.revokeObjectURL(url);
      });

      const copyBtn = document.getElementById('copy-console-btn') as HTMLButtonElement | null;
      copyBtn?.addEventListener('click', () => {
        console.log('Hotspots mapeados (primeros 10):', this.bloomingData.slice(0,10));
  alert('Data copied to console.');
      });
    }, 1000);
  }

  updateVisualization(): void {
    this.updateBloomingData();
    
    const geojson: FeatureCollection<Point, GeoJsonProperties> = {
      type: "FeatureCollection",
      features: this.bloomingData.map(hotspot => ({
        type: "Feature",
        geometry: { 
          type: "Point", 
          coordinates: [hotspot.lon, hotspot.lat] 
        },
        properties: { 
          name: hotspot.name,
          intensity: hotspot.intensity,
          status: hotspot.status,
          species: hotspot.species.join(', '),
          pollinatorCount: hotspot.pollinatorCount,
          bloomPeriod: hotspot.bloomPeriod
        }
      }))
    };

    (this.map.getSource('blooming-hotspots') as mapboxgl.GeoJSONSource)?.setData(geojson);
    
    // Actualizar estadísticas
    setTimeout(() => {
      const activeHotspotsEl = document.getElementById('active-hotspots');
      const totalPollinatorsEl = document.getElementById('total-pollinators');
      const riskZonesEl = document.getElementById('risk-zones');
      
      if (activeHotspotsEl) activeHotspotsEl.textContent = this.bloomingData.length.toString();
      if (totalPollinatorsEl) totalPollinatorsEl.textContent = this.getTotalPollinators().toLocaleString();
      if (riskZonesEl) riskZonesEl.textContent = this.getRiskZones().toString();
    }, 100);
  }

  getTotalPollinators(): number {
    return this.bloomingData.reduce((total, hotspot) => total + hotspot.pollinatorCount, 0);
  }

  getRiskZones(): number {
    return this.bloomingData.filter(hotspot => hotspot.intensity < 0.4).length;
  }

  getMonthName(month: number): string {
    const months = [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ];
    return months[month - 1];
  }

  triggerEmergencyProtocol(): void {
    // Simular protocolo de emergencia
    const modal = document.createElement('div');
    modal.style.cssText = `
      position: fixed; top: 0; left: 0; width: 100%; height: 100%; 
      background: rgba(0,0,0,0.8); display: flex; justify-content: center; 
      align-items: center; z-index: 10000;
    `;
    
    modal.innerHTML = `
      <div style="background: white; padding: 30px; border-radius: 10px; max-width: 500px; text-align: center;">
  <h2 style="color: #FF5722; margin-bottom: 20px;">🚨 Emergency</h2>
  <p style="margin-bottom: 20px;">Critical shortage detected in ${this.getRiskZones()} zones.</p>
        <div style="text-align: left; margin: 20px 0;">
          <h4>Immediate actions</h4>
          <ul>
            <li>Urgent sowing of melliferous species in critical zones</li>
            <li>Immediate redistribution of mobile hives</li>
            <li>Automatic alert to local beekeepers and authorities</li>
            <li>Intensive satellite monitoring for 30 days</li>
          </ul>
        </div>
        <button onclick="this.parentElement.parentElement.remove()" 
                style="padding: 10px 20px; background: #4CAF50; color: white; border: none; border-radius: 5px; cursor: pointer;">
          Accept
        </button>
      </div>
    `;
    
    document.body.appendChild(modal);
  }

  togglePanel(): void {
    this.panelCollapsed = !this.panelCollapsed;
  }

  toggleAnimation(): void {
    this.isAnimating = !this.isAnimating;
    if (this.isAnimating) {
      this.startBloomPulseAnimation();
    }
  }

  showTimelapseView(): void {
    // Toggle: iniciar/pausar timelapse
    if (this.timelapseRunning) {
      this.stopTimelapse();
      return;
    }
    this.startTimelapse();
  }

  startTimelapse(intervalMs: number = 800): void {
    if (this.timelapseRunning) return;
    this.timelapseRunning = true;
    let month = this.currentMonth || 1;
    // Buscar elementos del control para sincronizar la UI
    const slider = document.getElementById('monthSlider') as HTMLInputElement | null;
    const monthDisplay = document.getElementById('currentMonth');

    this.timelapseIntervalId = window.setInterval(() => {
      month = month < 12 ? month + 1 : 1;
      this.currentMonth = month;
      if (slider) slider.value = String(month);
      if (monthDisplay) monthDisplay.textContent = this.getMonthName(month);
      this.updateVisualization();
    }, intervalMs) as any;
  }

  stopTimelapse(): void {
    if (!this.timelapseRunning) return;
    this.timelapseRunning = false;
    if (this.timelapseIntervalId) {
      clearInterval(this.timelapseIntervalId as any);
      this.timelapseIntervalId = null;
    }
    // opcional: restaurar mes por defecto
    this.currentMonth = 5;
    const slider = document.getElementById('monthSlider') as HTMLInputElement | null;
    const monthDisplay = document.getElementById('currentMonth');
    if (slider) slider.value = String(this.currentMonth);
    if (monthDisplay) monthDisplay.textContent = this.getMonthName(this.currentMonth);
    this.updateVisualization();
  }

  private simulateLoading(): void {
    // Simular proceso de carga
    const loadingSteps = [
      { progress: 20, message: "Conectando con satélites..." },
      { progress: 40, message: "Procesando imágenes MODIS..." },
      { progress: 60, message: "Analizando datos de floración..." },
      { progress: 80, message: "Calculando rutas de polinizadores..." },
      { progress: 100, message: "¡Demo lista!" }
    ];

    let currentStep = 0;
    const loadingInterval = setInterval(() => {
      if (currentStep < loadingSteps.length) {
        this.loadingProgress = loadingSteps[currentStep].progress;
        currentStep++;
      } else {
        clearInterval(loadingInterval);
        setTimeout(() => {
          this.isLoading = false;
        }, 500);
      }
    }, 1000);
  }

  // Función que llama a la API de Mapbox para geocodificar y volar al lugar  
  async flyToRegion(name: string) {
    try {
      const response = await fetch(
        `https://api.mapbox.com/geocoding/v5/mapbox.places/${encodeURIComponent(name)}.json?access_token=pk.eyJ1Ijoic2FoaXZhIiwiYSI6ImNtZzl3cXFwaDBpOG8ybHNneGFwZ3ZqOTUifQ.UrldzEHRjHkw2CiMeAyR-Q`
      );
      const data = await response.json();

      if (data.features && data.features.length > 0) {
        const [lng, lat] = data.features[0].center;
        this.map.flyTo({
          center: [lng, lat],
          zoom: 8,
          speed: 0.8,
          curve: 1.5
        });
      } else {
  alert('Region not found.');
      }
    } catch (error) {
      console.error('Error geocodificando la región:', error);
  alert('Error geocoding the region.');
    }
  }
}
